source "http://rubygems.org"

gem 'cucumber'
gem 'selenium-webdriver'
gem 'capybara'
gem 'rspec'
gem 'nokogiri'
gem 'shoulda'
gem 'webrat'
gem 'thor'
gem 'poltergeist'  # headless gem hook
gem 'launchy'     # screenshot gem