$:.unshift(File.dirname(__FILE__) + '')
require 'cucumber/rake/task'
require 'rspec/core/rake_task'

desc "Run all examples"
RSpec::Core::RakeTask.new(:spec) do |t|
  t.rspec_opts = %w{--color}
end

Cucumber::Rake::Task.new(:cucumber) do |task|
  task.cucumber_opts = %w{--format pretty}
end

Cucumber::Rake::Task.new(:cucumber_screenshot) do |task|
   task.cucumber_opts = %w{--format html --out report.html}
end

task :default => [:cucumber, :spec]